env:
  commonjs: true
  es2021: true
  node: true
  mocha: true
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
rules: {'no-unused-vars': ['error', { argsIgnorePattern: 'next' }]}
