name: main action
on:
  push:
    branches:
    - main

jobs:
  run-eslint:
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: npm install
      - name: check linting error
        run: npm run eslint
        
      
  
